<?IncludeTemplateLangFile(__FILE__);?>	
</div>
                    </div>
                </div>
            </div>      
            <?if($APPLICATION->GetCurDir() == '/'){?>
                <div class="container bs-docs-container wcag" role="complementary" id="complementary_content"><div class="row"><div class="col-md-12"><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:news.list", "front-big-banners", Array("IBLOCK_TYPE" => "aspro_allcorp_content",
		"IBLOCK_ID" => CCache::$arIBlocks[SITE_ID]["aspro_allcorp_content"]["aspro_allcorp_advt"][0],
		"NEWS_COUNT" => "30",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "arrFilterBanners",
		"FIELD_CODE" => array(
			0 => "PREVIEW_TEXT",
			1 => "PREVIEW_PICTURE",
			2 => "DETAIL_TEXT",
			3 => "DETAIL_PICTURE",
			4 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "BANNERTYPE",
			2 => "TEXTCOLOR",
			3 => "LINKIMG",
			4 => "BUTTON1TEXT",
			5 => "BUTTON1LINK",
			6 => "BUTTON2TEXT",
			7 => "BUTTON2LINK",
			8 => "link",
			9 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "N",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "front-big-banners",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"MIBOK_SPECIAL_KEY" => "9ca9f1eba3c3f92d167a56c572695c81"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/under_sidebar.php",
		"MIBOK_SPECIAL_KEY" => "1cca4e99ff8e6758ac5724aa5bbf7a32"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/under_sidebar.php",
		"MIBOK_SPECIAL_KEY" => "1cca4e99ff8e6758ac5724aa5bbf7a32"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/front-services.php",
		"EDIT_TEMPLATE" => "standard.php",
		"MIBOK_SPECIAL_KEY" => "42e754943d0573587f7d4f74f6cb889e"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:news.list", "front-services", Array("IBLOCK_TYPE" => "aspro_allcorp_content",
		"IBLOCK_ID" => CCache::$arIBlocks[SITE_ID]["aspro_allcorp_content"]["aspro_allcorp_main-links"][0],
		"NEWS_COUNT" => "30",
		"SORT_BY1" => "SORT",
		"SORT_ORDER1" => "ASC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "NAME",
			1 => "PREVIEW_TEXT",
			2 => "PREVIEW_PICTURE",
			3 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "ICON",
			2 => "LINK",
			3 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "N",
		"COLUMN_COUNT" => "3",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "front-services",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"MIBOK_SPECIAL_KEY" => "2dcecab04e17ca5000c28814c8be21d2"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/front-catalog.php",
		"EDIT_TEMPLATE" => "standard.php",
		"MIBOK_SPECIAL_KEY" => "6e9fae07f4db9a71d0831a40e43dd688"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:news.list", "catalog-sections", Array("IBLOCK_TYPE" => "aspro_allcorp_catalog",
		"IBLOCK_ID" => CCache::$arIBlocks[SITE_ID]["aspro_allcorp_catalog"]["aspro_allcorp_catalog"][0],
		"NEWS_COUNT" => "20",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "",
			1 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "d.m.Y",
		"SET_TITLE" => "Y",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "Y",
		"ADD_SECTIONS_CHAIN" => "Y",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "Y",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "Y",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "Y",
		"VIEW_TYPE" => "list",
		"COUNT_IN_LINE" => "3",
		"IMAGE_POSITION" => "left",
		"AJAX_OPTION_ADDITIONAL" => "",
		"MIBOK_SPECIAL_KEY" => "bbd5a75bd8e038d833c7711bfa1b59c8"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/front-about.php",
		"EDIT_TEMPLATE" => "standard.php",
		"MIBOK_SPECIAL_KEY" => "25462fa05a77cda5db2b6123e58cfe35"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:news.list", "front-news", Array("IBLOCK_TYPE" => "aspro_allcorp_content",
		"IBLOCK_ID" => CCache::$arIBlocks[SITE_ID]["aspro_allcorp_content"]["aspro_allcorp_news"][0],
		"NEWS_COUNT" => "4",
		"SORT_BY1" => "ACTIVE_FROM",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "SORT",
		"SORT_ORDER2" => "ASC",
		"FILTER_NAME" => "",
		"FIELD_CODE" => array(
			0 => "DETAIL_TEXT",
			1 => "DETAIL_PICTURE",
			2 => "",
		),
		"PROPERTY_CODE" => array(
			0 => "",
			1 => "",
		),
		"CHECK_DATES" => "Y",
		"DETAIL_URL" => "",
		"AJAX_MODE" => "N",
		"AJAX_OPTION_JUMP" => "N",
		"AJAX_OPTION_STYLE" => "Y",
		"AJAX_OPTION_HISTORY" => "N",
		"CACHE_TYPE" => "A",
		"CACHE_TIME" => "3600000",
		"CACHE_FILTER" => "Y",
		"CACHE_GROUPS" => "N",
		"PREVIEW_TRUNCATE_LEN" => "",
		"ACTIVE_DATE_FORMAT" => "j F Y",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "N",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"ADD_SECTIONS_CHAIN" => "N",
		"HIDE_LINK_WHEN_NO_DETAIL" => "N",
		"PARENT_SECTION" => "",
		"PARENT_SECTION_CODE" => "",
		"INCLUDE_SUBSECTIONS" => "Y",
		"PAGER_TEMPLATE" => ".default",
		"DISPLAY_TOP_PAGER" => "N",
		"DISPLAY_BOTTOM_PAGER" => "N",
		"PAGER_TITLE" => "Новости",
		"PAGER_SHOW_ALWAYS" => "N",
		"PAGER_DESC_NUMBERING" => "N",
		"PAGER_DESC_NUMBERING_CACHE_TIME" => "3600000",
		"PAGER_SHOW_ALL" => "N",
		"AJAX_OPTION_ADDITIONAL" => "",
		"COMPONENT_TEMPLATE" => "front-news",
		"SET_BROWSER_TITLE" => "Y",
		"SET_META_KEYWORDS" => "Y",
		"SET_META_DESCRIPTION" => "Y",
		"SET_LAST_MODIFIED" => "N",
		"STRICT_SECTION_CHECK" => "N",
		"COMPOSITE_FRAME_MODE" => "A",
		"COMPOSITE_FRAME_TYPE" => "AUTO",
		"PAGER_BASE_LINK_ENABLE" => "N",
		"SHOW_404" => "N",
		"MESSAGE_404" => "",
		"MIBOK_SPECIAL_KEY" => "a2b2c1560200922effa8ab88ebc1b6f1"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:news.list", "catalog-main", Array("PARENT_SECTION" => "0",
		"COUNT_IN_LINE" => "4",
		"VIEW_TYPE" => "table",
		"SHOW_TABS" => "",
		"SHOW_NAME" => "Y",
		"SHOW_DETAIL" => "Y",
		"SHOW_IMAGE" => "Y",
		"IMAGE_POSITION" => "top",
		"IBLOCK_TYPE" => "aspro_allcorp_catalog",
		"IBLOCK_ID" => "11",
		"NEWS_COUNT" => "20",
		"SORT_BY1" => "ID",
		"SORT_ORDER1" => "DESC",
		"SORT_BY2" => "ID",
		"SORT_ORDER2" => "DESC",
		"SET_TITLE" => "N",
		"SET_STATUS_404" => "Y",
		"INCLUDE_IBLOCK_INTO_CHAIN" => "N",
		"DISPLAY_NAME" => "Y",
		"PREVIEW_TRUNCATE_LEN" => "0",
		"MIBOK_SPECIAL_KEY" => "12bf2ec95aac22e995273dd376bb920e"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => SITE_DIR."include/under_sidebar.php",
		"MIBOK_SPECIAL_KEY" => "1cca4e99ff8e6758ac5724aa5bbf7a32"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => "/include/calc.php",
		"MIBOK_SPECIAL_KEY" => "c5315307db399e05f29b3537ed9e7a09"));?></div><div class="bs-docs-section"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file",
		"PATH" => "/include/zayavki.php",
		"MIBOK_SPECIAL_KEY" => "623cd94c5b3ee6c66198050c85b41e60"));?></div></div></div></div>            
            <?}?>
            <footer class="bs-docs-footer" role="contentinfo">
                <div class="container wcag">
                    <div class="panel-group">
                        <button type="button" class="btn btn-default go-top" tabindex="0" aria-label="<?=GetMessage('GO_TOP_BUTTON_TITLE')?>"><span class="glyphicon glyphicon-circle-arrow-up"></span>&nbsp;<?=GetMessage('GO_TOP_BUTTON_TITLE')?><span class="hover"></span></button>
                    </div>    
                    <?$APPLICATION->IncludeComponent("bitrix:menu", ".default", Array("ROOT_MENU_TYPE" => "bottom",
		"MENU_CACHE_TYPE" => "A",
		"MENU_CACHE_TIME" => "3600",
		"MENU_CACHE_USE_GROUPS" => "Y",
		"MENU_CACHE_GET_VARS" => "",
		"MAX_LEVEL" => "2",
		"CHILD_MENU_TYPE" => "",
		"USE_EXT" => "N",
		"DELAY" => "N",
		"ALLOW_MULTI_SELECT" => "N",
		"MIBOK_SPECIAL_KEY" => "12596d26cd6e18621ed6007cea88d77a"));?>
					<?if(CModule::IncludeModule('advertising')):?>
                                   
					<?endif;?>					
                    <div class="row">
                        <div class="col-md-12" tabindex="0">
                            <div class="address"><strong><?=GetMessage('SITE_ADDRESS')?>:</strong> <?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file", "PATH" => SITE_DIR."glaza_mibok_include/site_address.php", "MIBOK_SPECIAL_COMPARE" => "N"));?></div>
                            <div class="address"><strong><?=GetMessage('SITE_EMAIL')?>:</strong> <?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file", "PATH" => SITE_DIR."glaza_mibok_include/site_email.php", "MIBOK_SPECIAL_COMPARE" => "N"));?></div>
                            <div class="address"><strong><?=GetMessage('SITE_PHONE')?>:</strong> <?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file", "PATH" => SITE_DIR."glaza_mibok_include/site_phone.php", "MIBOK_SPECIAL_COMPARE" => "N"));?></div>
                        </div>
                    </div>
                    <div class="row">                        
                        <div class="col-md-12">
                            <div class="copy"><?$APPLICATION->IncludeComponent("bitrix:main.include", "", Array("AREA_FILE_SHOW" => "file", "PATH" => SITE_DIR."glaza_mibok_include/site_copy.php", "MIBOK_SPECIAL_COMPARE" => "N"));?></div>
                        </div>
                    </div>
                </div>                 
            </footer>
        </div>        
		
		
		
		
        <script src="<?=SITE_TEMPLATE_PATH?>/js/libs/jquery.scrollTo-min.js"></script>
        <script src="<?=SITE_TEMPLATE_PATH?>/js/libs/jquery.form.min.js"></script>
        <script src="<?=SITE_TEMPLATE_PATH?>/js/toolbar.js"></script>
        <script src="<?=SITE_TEMPLATE_PATH?>/js/menu.js"></script>
        <script src="<?=SITE_TEMPLATE_PATH?>/js/app.js"></script>
        <?$APPLICATION->IncludeComponent("mibok:special_check_auth", "", array("MIBOK_SPECIAL_COMPARE" => "N"))?>
		
		<?
		if(COption::GetOptionString('mibok.glaza', 'voice')  == 'Y'){
			?>
            <audio id='start_sound' src='http://glaza.mibok.ru/voice/start_voice.mp3' preload data-process='<?=SITE_TEMPLATE_PATH.'/ajax/get_voice.php'?>'></audio>
			<script src='<?=SITE_TEMPLATE_PATH?>/js/voice.js' type='application/javascript'></script>
			<?
		}
		?>
        <script src="<?=SITE_TEMPLATE_PATH?>/js/custom.js"></script>
    </body>
</html>
